-- Billo SMS database schema reference.
-- The running application creates/migrates this schema additively in database.py.
-- Do not DROP or TRUNCATE production tables.
CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY,username TEXT NOT NULL UNIQUE,password_hash TEXT NOT NULL,role TEXT NOT NULL,parent_id INTEGER,full_name TEXT DEFAULT '',email TEXT DEFAULT '',whatsapp TEXT DEFAULT '',telegram TEXT DEFAULT '',profile_photo TEXT DEFAULT '',profile_photo_type TEXT DEFAULT '',theme TEXT NOT NULL DEFAULT 'Billo Original',music_enabled INTEGER NOT NULL DEFAULT 1,music_volume REAL NOT NULL DEFAULT 0.18,active INTEGER NOT NULL DEFAULT 1,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS ranges(id INTEGER PRIMARY KEY,name TEXT NOT NULL UNIQUE,country TEXT NOT NULL DEFAULT 'Other',country_code TEXT DEFAULT '',rate REAL NOT NULL DEFAULT 0,active INTEGER NOT NULL DEFAULT 1,created_at TEXT NOT NULL,deleted_at TEXT);
CREATE TABLE IF NOT EXISTS numbers(id INTEGER PRIMARY KEY,range_id INTEGER NOT NULL,value TEXT NOT NULL UNIQUE,country TEXT NOT NULL DEFAULT 'Other',country_code TEXT DEFAULT '',active INTEGER NOT NULL DEFAULT 1,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS allocations(id INTEGER PRIMARY KEY,number_id INTEGER NOT NULL,target_user_id INTEGER NOT NULL,parent_allocation_id INTEGER,payout REAL NOT NULL,term TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'ACTIVE',allocated_at TEXT NOT NULL,unallocated_at TEXT);
CREATE TABLE IF NOT EXISTS carriers(id INTEGER PRIMARY KEY,name TEXT NOT NULL UNIQUE,method TEXT NOT NULL DEFAULT 'POST',status TEXT NOT NULL DEFAULT 'ACTIVE',field_from TEXT NOT NULL DEFAULT 'from',field_to TEXT NOT NULL DEFAULT 'to',field_message TEXT NOT NULL DEFAULT 'message',field_sms_id TEXT NOT NULL DEFAULT 'sms_id',created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS carrier_ips(id INTEGER PRIMARY KEY,carrier_id INTEGER NOT NULL,cidr TEXT NOT NULL,UNIQUE(carrier_id,cidr));
CREATE TABLE IF NOT EXISTS sms_cdr(id INTEGER PRIMARY KEY,sms_id TEXT NOT NULL UNIQUE,carrier_id INTEGER,number TEXT NOT NULL,cli TEXT NOT NULL,message TEXT NOT NULL,range_id INTEGER,range_name_snapshot TEXT DEFAULT '',rate_snapshot REAL NOT NULL DEFAULT 0,client_id INTEGER,agent_id INTEGER,manager_id INTEGER,received_at TEXT NOT NULL);
